apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ .Values.application }}
    envName: {{ .Values.global.envName }}
    serviceName: {{ .Values.serviceName }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
  selector:
    app: {{ .Values.application }}
    envName: {{ .Values.global.envName }}
    serviceName: {{ .Values.serviceName }}
