global:
  envName: dev
  namespace: default
  image:
    server: registry.local
    repo: development
    tag: latest
    pullPolicy: IfNotPresent
    useSecret: false
    pullSecret: na
ingress:
  # If fqdn is provided, it takes precedence over the separate host and domain.
  fqdn: localhost
  host: mern-example-dev
  domain: client.local
  useTls: true
  # The SSL cert that will be used to provide TLS.
  tlsSecret:
  class: nginx
  path: /

apiUrl: /api

# How many pods to start
replicaCount: 1

# Restrict the pods to specific nodes if necessary
nodeSelector: {}

# Readiness checks and liveness checks are disabled in local dev
enableChecks: true

resources:
  requests:
    cpu: 70m
    memory: 50Mi
  limits:
    memory: 100Mi

# Base values should not need to override
application: mern-example
serviceName: client
dockerImageName: client

# Base values should not need to override
service:
  externalPort: 3000
  internalPort: 3000
